name: Nautilus-Test-Plugin
version: ${version}
main: win.obydux.testplugin.TestPlugin
description: Nautilus Test Plugin
author: Obydux
api-version: ${apiversion}
load: STARTUP
#bootstrapper: org.purpurmc.testplugin.TestPluginBootstrap
#loader: org.purpurmc.testplugin.TestPluginLoader
defaultPerm: FALSE
permissions:
dependencies:
